# force old non-container infrastructure, to see whether this
# is the reason why the IO test hangs
git:
  depth: 3
language: cpp
compiler: clang
os: 
  - osx
script:
  - cmake --version
  - python fips build osx-make-debug
  - python fips build osx-make-release
  - python fips build metal-osx-make-debug
  - python fips build metal-osx-make-release
  # these iOS configs are actually Metal
  - python fips build ios-xcode-debug
  - python fips build ios-xcode-release


