# force old non-container infrastructure, to see whether this
# is the reason why the IO test hangs
git:
  depth: 3
language: cpp
compiler: clang
os: 
  - osx
script:
  - python fips build osx-make-debug
