# force old non-container infrastructure, to see whether this
# is the reason why the IO test hangs
git:
  depth: 3
language: cpp
compiler: gcc
os: 
  - osx
  - linux
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libglu1-mesa-dev
      - xorg-dev
script:
  - echo $TRAVIS_OS_NAME
  - cmake --version
  - gcc --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build osx-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build osx-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build metal-osx-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build metal-osx-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build sapp-metal-osx-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build sapp-metal-osx-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build linux-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build linux-make-release; fi
